---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: Lors de la migration des données de stockage, les systèmes back-end sont intégrés manuellement via des API REST. Lors de la migration des données VASA Provider, les données sont exportées à partir de la base de données Derby existante et importées dans la base de données MongoDB. 
---
= Migrez des outils ONTAP pour VMware vSphere 9.xx vers la version 10.3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le déplacement des outils NetApp ONTAP pour la configuration de VMware vSphere de la version 9.xx vers la version 10.x nécessite un processus de migration en raison des mises à jour et des améliorations importantes du produit entre les versions.

Vous pouvez effectuer la migration à partir des outils ONTAP pour VMware vSphere 9.12D1 et 9.13D2 vers la version 10.3.

Si votre configuration contient des banques de données NFS et VMFS, mais aucune banque de données vVols, désinstallez simplement ONTAP Tools 9.xx et déployez ONTAP Tools 10.x. En revanche, si votre configuration contient des banques de données vVols, vous devrez migrer le fournisseur VASA et le SRA.

Le tableau suivant décrit le processus de migration dans ces deux scénarios différents.

|===
| *Si la configuration dispose de magasins de données vVols* | *Si la configuration contient uniquement des banques de données NFS et VMFS* 


| Étapes : 1. link:../migrate/sra-vasa-migration.html["Migrer le fournisseur VASA"] 2.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Créer des politiques de stockage de machines virtuelles"] | Étapes : 1. Supprimez les outils ONTAP 9.xx de votre environnement. Consultez  https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_How_to_remove_OTV_9_12_from_your_environment["Comment supprimer OTV 9.xx de votre environnement"] Article de la base de connaissances NetApp. 2. link:../deploy/quick-start.html["Déployer et configurer les outils ONTAP pour VMware vSphere 10.3"] 3. link:../migrate/sra-vasa-migration.html["Mettre à jour le SRA"] 4.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Créer des politiques de stockage de machines virtuelles"] 
|===

NOTE: Après la migration des outils ONTAP pour VMware vSphere 9.xx vers la version 10.3, les datastores vVols utilisant le protocole NVMe/FC ne deviennent plus opérationnels, car les outils ONTAP 10.3 prennent en charge le protocole NVMe-of uniquement avec les datastores VMFS.
