---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez configurer les intervalles de délai de stockage en fonction des paramètres recommandés pour Storage Replication adapter \(SRA\) afin de garantir des performances optimales dans des environnements hautement évolutifs.' 
---
= Configurez SRA pour les environnements hautement évolutifs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer les intervalles de délai d'expiration du stockage conformément aux paramètres recommandés pour Storage Replication adapter (SRA) afin de garantir des performances optimales dans des environnements hautement évolutifs.



== Paramètres du fournisseur de stockage

Vous devez définir les valeurs de temporisation suivantes sur VMware Live site Recovery pour un environnement évolutif :

|===


| *Paramètres avancés* | *Valeurs de temporisation* 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
Augmentez la valeur du réglage de 900 à 12000 secondes.



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
Définir une valeur élevée (par exemple : 99999)

|===
Vous devez également activer `StorageProvider.autoResignatureMode` l'option.

Pour plus d'informations sur la modification des paramètres du fournisseur de stockage, reportez-vous à la section https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-provider-settings.html["Modifier les paramètres du fournisseur de stockage"].



== Paramètres de stockage

Lorsque vous appuyez sur une temporisation, augmentez les valeurs de `storage.commandTimeout` et `storage.maxConcurrentCommandCnt` à une valeur supérieure.


NOTE: L'intervalle de temporisation spécifié est la valeur maximale. Il n'est pas nécessaire d'attendre que le délai maximum soit atteint. La plupart des commandes se terminent dans l'intervalle maximal défini de temps d'attente.

Pour modifier les paramètres du fournisseur SAN, reportez-vous à la section https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-settings.html["Modifier les paramètres de stockage"].
