---
permalink: protect/enable-storage-replication-adapter.html 
sidebar: sidebar 
keywords:  
summary: 'Les outils ONTAP pour VMware vSphere permettent d"activer la fonctionnalité SRA pour configurer la reprise après incident.' 
---
= Activez SRA pour protéger les datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils ONTAP pour VMware vSphere permettent d'activer la fonctionnalité SRA pour configurer la reprise après incident.

.Avant de commencer
* Vous devez avoir configuré votre instance vCenter Server et votre hôte ESXi.
* Vous devez avoir déployé des outils ONTAP pour VMware vSphere.
* Vous devez avoir téléchargé le `.tar.gz` fichier de l'adaptateur SRA à partir du https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab["Site de support NetApp"^].
* Les clusters ONTAP source et destination doivent avoir la même planification SnapMirror personnalisée que celle créée avant d'exécuter les workflows SRA.


.Étapes
. Connectez-vous à l'interface de gestion de l'appliance VMware Live site Recovery à l'aide de `\https://:<srm_ip>:5480` l'URL :, puis accédez à Storage Replication Adapters dans l'interface de gestion de l'appliance VMware VMware Live site Recovery.
. Sélectionnez *nouvel adaptateur*.
. Téléchargez le programme d'installation _.tar.gz_ du plug-in SRA vers VMware Live site Recovery.
. Relancez la recherche des adaptateurs pour vérifier que les détails sont mis à jour sur la page adaptateurs de réplication de stockage de VMware Live site Recovery.

