---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: 'Pour que VMware Live site Recovery puisse communiquer avec SRA, vous devez mettre à jour les informations d"identification SRA sur le serveur VMware Live site Recovery si vous avez modifié les informations d"identification.' 
---
= Mettez à jour les informations d'identification SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour que VMware Live site Recovery puisse communiquer avec SRA, vous devez mettre à jour les informations d'identification SRA sur le serveur VMware Live site Recovery si vous avez modifié les informations d'identification.

.Avant de commencer
Vous devez avoir exécuté les étapes mentionnées dans la rubrique link:../protect/configure-on-srm-appliance.html["Configuration de SRA sur l'appliance VMware Live site Recovery"].

.Étapes
. Exécutez les commandes suivantes pour supprimer le dossier de la machine de restauration de site direct VMware Outils ONTAP mis en cache nom d'utilisateur mot de passe :
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Exécutez la commande Perl pour configurer SRA avec les nouvelles informations d'identification :
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` Vous devez avoir un devis unique autour de la valeur du mot de passe.
+
Un message de confirmation de la mémorisation des identifiants de stockage s'affiche. SRA peut communiquer avec le serveur SRA à l'aide de l'adresse IP, du port et des informations d'identification fournis.




