---
permalink: concepts/rbac-ontap-use.html 
sidebar: sidebar 
keywords: ontap rbac, use ontap rbac 
summary: 'Il existe plusieurs aspects des outils ONTAP pour l"implémentation de VMware vSphere 10 RBAC avec ONTAP que vous devez prendre en compte avant de l"utiliser dans un environnement de production.' 
---
= Utilisez ONTAP RBAC avec les outils ONTAP pour VMware vSphere 10
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe plusieurs aspects des outils ONTAP pour l'implémentation de VMware vSphere 10 RBAC avec ONTAP que vous devez prendre en compte avant de l'utiliser dans un environnement de production.



== Présentation du processus de configuration

Les outils ONTAP pour VMware vSphere 10 incluent la prise en charge de la création d'un utilisateur ONTAP avec un rôle personnalisé. Ces définitions sont fournies dans un fichier JSON que vous pouvez télécharger vers le cluster ONTAP. Vous pouvez créer l'utilisateur et adapter le rôle à vos besoins en matière d'environnement et de sécurité.

Les principales étapes de configuration sont décrites ci-dessous à un niveau élevé. Voir link:../configure/configure-user-role-and-privileges.html["Configurer les rôles et privilèges des utilisateurs ONTAP"]pour plus de détails.

.1. Préparation
Vous devez disposer d'informations d'identification d'administration pour le gestionnaire d'outils ONTAP et le cluster ONTAP.

.2. Téléchargez le fichier de définition JSON
Une fois connecté à l'interface utilisateur du Gestionnaire d'outils ONTAP, vous pouvez télécharger le fichier JSON contenant les définitions RBAC.

.3. Créez un utilisateur ONTAP avec un rôle
Une fois connecté à System Manager, vous pouvez créer l'utilisateur et le rôle :

. Sélectionnez *Cluster* sur la gauche, puis *Settings*.
. Faites défiler jusqu'à *utilisateurs et rôles* et cliquez sur `-->`.
. Sélectionnez *Ajouter* sous *utilisateurs* et sélectionnez *produits de virtualisation*.
. Sélectionnez le fichier JSON sur votre poste de travail local et chargez-le.


.4. Configurez le rôle
Dans le cadre de la définition du rôle, vous devez prendre plusieurs décisions administratives. Voir <<Configurez le rôle à l'aide de System Manager>> pour plus de détails.



== Configurez le rôle à l'aide de System Manager

Une fois que vous avez commencé à créer un utilisateur et un rôle avec System Manager et que vous avez téléchargé le fichier JSON, vous pouvez personnaliser le rôle en fonction de votre environnement et de vos besoins.



=== Configuration de l'utilisateur principal et du rôle

Les définitions RBAC sont packagées sous la forme de plusieurs fonctionnalités, dont une combinaison de VSC, VASA Provider et SRA. Vous devez sélectionner l'environnement ou les environnements dans lesquels vous avez besoin de la prise en charge de RBAC. Par exemple, si vous souhaitez que les rôles prennent en charge la fonctionnalité de plug-in à distance, sélectionnez VSC. Vous devez également choisir le nom d'utilisateur et le mot de passe associé.



=== Privilèges

Les Privileges de rôle sont organisés en quatre ensembles en fonction du niveau d'accès requis au stockage ONTAP. Le Privileges sur lequel sont basés les rôles comprend :

* Détection
+
Il permet donc d'ajouter des systèmes de stockage.

* Créer du stockage
+
Grâce à ce rôle, vous pouvez créer du stockage. Il inclut également toutes les Privileges associées au rôle de découverte.

* Modifier le stockage
+
Ce rôle vous permet de modifier le stockage. Il inclut également toutes les Privileges associées à la détection et crée des rôles de stockage.

* Détruire le stockage
+
Vous pouvez ainsi détruire le stockage. Elle inclut également toutes les Privileges associées à la détection, la création du stockage et la modification des rôles de stockage.





=== Générer l'utilisateur avec un rôle

Après avoir sélectionné les options de configuration pour votre environnement, cliquez sur *Ajouter* et ONTAP crée l'utilisateur et le rôle. Le nom du rôle généré est une concaténation des valeurs suivantes :

* Valeur de préfixe constante définie dans le fichier JSON (par exemple « OTV_10 »)
* Fonctionnalité de produit que vous avez sélectionnée
* Liste des jeux de privilèges.


.Exemple
`OTV_10_VSC_Discovery_Create`

Le nouvel utilisateur sera ajouté à la liste de la page "utilisateurs et rôles". Notez que les méthodes de connexion utilisateur HTTP et ONTAPI sont prises en charge.
