---
permalink: concepts/rbac-learn-about.html 
sidebar: sidebar 
keywords: role based access control, rbac, rbac components, learn about rbac 
summary: 'Le contrôle d"accès basé sur des rôles (RBAC) est un framework de sécurité qui permet de contrôler l"accès aux ressources au sein d"une entreprise. Le contrôle d"accès basé sur des rôles simplifie l"administration en définissant des rôles disposant de niveaux d"autorisation spécifiques pour effectuer des actions, au lieu d"attribuer des autorisations à des utilisateurs individuels. Les rôles définis sont attribués aux utilisateurs, ce qui permet de réduire le risque d"erreur et simplifie la gestion du contrôle d"accès dans l"ensemble de votre organisation.' 
---
= Découvrez les outils ONTAP pour VMware vSphere 10 RBAC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le contrôle d'accès basé sur des rôles (RBAC) est un framework de sécurité qui permet de contrôler l'accès aux ressources au sein d'une entreprise. Le contrôle d'accès basé sur des rôles simplifie l'administration en définissant des rôles disposant de niveaux d'autorisation spécifiques pour effectuer des actions, au lieu d'attribuer des autorisations à des utilisateurs individuels. Les rôles définis sont attribués aux utilisateurs, ce qui permet de réduire le risque d'erreur et simplifie la gestion du contrôle d'accès dans l'ensemble de votre organisation.

Le modèle standard RBAC se compose de plusieurs technologies d'implémentation ou phases de plus en plus complexes. Il en résulte que les déploiements RBAC réels, basés sur les besoins des fournisseurs de logiciels et de leurs clients, peuvent différer et aller de relativement simple à très complexe.



== Composants RBAC

À un niveau élevé, plusieurs composants sont généralement inclus dans chaque implémentation de RBAC. Ces composants sont liés de différentes manières dans le cadre de la définition des processus d'autorisation.

.Privilèges
Un _privilège_ est une action ou une capacité qui peut être autorisée ou refusée. Il peut s'agir d'une opération simple telle que la capacité de lire un fichier ou une opération plus abstraite spécifique à un système logiciel donné. Vous pouvez également définir Privileges pour limiter l'accès aux terminaux de l'API REST et aux commandes de l'interface de ligne de commande. Chaque implémentation de RBAC inclut une Privileges prédéfinie et peut également permettre aux administrateurs de créer une Privileges personnalisée.

.Rôles
Un _role_ est un conteneur qui inclut un ou plusieurs Privileges. Les rôles sont généralement définis en fonction de tâches ou de fonctions particulières. Lorsqu'un rôle est attribué à un utilisateur, tous les Privileges contenus dans le rôle lui sont attribués. Comme avec Privileges, les implémentations incluent des rôles prédéfinis et permettent généralement de créer des rôles personnalisés.

.Objets
Un _objet_ représente une ressource réelle ou abstraite identifiée dans l'environnement RBAC. Les actions définies via la Privileges sont effectuées sur ou avec les objets associés. Selon l'implémentation, Privileges peut être accordé à un type d'objet ou à une instance d'objet spécifique.

.Utilisateurs et groupes
_Users_ sont affectés ou associés à un rôle appliqué après l'authentification. Certaines implémentations RBAC ne permettent d'attribuer qu'un seul rôle à un utilisateur, tandis que d'autres autorisent plusieurs rôles par utilisateur, peut-être avec un seul rôle actif à la fois. L'attribution de rôles à des _groupes_ peut simplifier davantage l'administration de la sécurité.

.Autorisations
Une _permission_ est une définition qui lie un utilisateur ou un groupe avec un rôle à un objet. Les autorisations peuvent être utiles avec un modèle d'objet hiérarchique dans lequel elles peuvent éventuellement être héritées par les enfants de la hiérarchie.



== Deux environnements RBAC

Il existe deux environnements RBAC distincts que vous devez prendre en compte lorsque vous utilisez les outils ONTAP pour VMware vSphere 10.

.Serveur VMware vCenter
L'implémentation RBAC dans VMware vCenter Server permet de restreindre l'accès aux objets exposés via l'interface utilisateur du client vSphere. Dans le cadre de l'installation des outils ONTAP pour VMware vSphere 10, l'environnement RBAC est étendu pour inclure des objets supplémentaires représentant les fonctionnalités des outils ONTAP. L'accès à ces objets est fourni via le plug-in distant. Pour plus d'informations, reportez-vous à la section.link:../concepts/rbac-vcenter-environment.html["Environnement RBAC du serveur vCenter"]

.Groupe ONTAP
Les outils ONTAP pour VMware vSphere 10 se connectent à un cluster ONTAP via l'API REST ONTAP pour effectuer des opérations de stockage. L'accès aux ressources de stockage est contrôlé via un rôle ONTAP associé à l'utilisateur ONTAP lors de l'authentification. Voir link:../concepts/rbac-ontap-environment.html["Environnement ONTAP RBAC"] pour plus d'informations.
