---
permalink: manage/collect-the-log-files.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez collecter les fichiers journaux des outils ONTAP pour VMware vSphere à partir des options disponibles dans l"interface utilisateur graphique \(GUI\) des outils ONTAP pour VMware vSphere. Le support technique peut vous demander de collecter les fichiers journaux afin de résoudre un problème.' 
---
= Collectez les fichiers journaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez collecter les fichiers journaux des outils ONTAP pour VMware vSphere à partir des options disponibles dans l'interface utilisateur de ONTAP Tools Manager. Le support technique peut vous demander de collecter les fichiers journaux afin de résoudre un problème.


NOTE: La génération de journaux à partir du Gestionnaire d'outils ONTAP inclut tous les journaux de toutes les instances de vCenter Server. La génération des journaux à partir de l'interface utilisateur du client vCenter est étendue pour le serveur vCenter sélectionné.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *Log Bundles* dans la barre latérale.
+
Cette opération peut prendre plusieurs minutes.

. Sélectionnez *générer* pour générer les fichiers journaux.
. Saisissez le libellé du lot de journaux et sélectionnez *Generate*.
+
Téléchargez le fichier tar.gz et envoyez-le au support technique.



Pour générer un bundle de journaux à l'aide de l'interface utilisateur du client vCenter, procédez comme suit :

.Étapes
. Connectez-vous au client vSphere
. Depuis la page d'accueil de vSphere client, accédez à *support* > *Log bundle* > *Generate*.
. Indiquez l'étiquette de l'ensemble de journaux et générez l'ensemble de journaux. Vous pouvez voir l'option de téléchargement lorsque les fichiers sont générés. Le téléchargement peut prendre un certain temps.



NOTE: L'ensemble de journaux généré remplace l'ensemble de journaux généré au cours des 3 derniers jours ou des 72 dernières heures.
