---
permalink: manage/configure-remote-diagnostic-access.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez configurer les outils ONTAP pour VMware vSphere afin d"activer l"accès SSH pour l"utilisateur diag.' 
---
= Configurer l'accès aux diagnostics à distance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer les outils ONTAP pour VMware vSphere afin d'activer l'accès SSH pour l'utilisateur diag.

.Avant de commencer
L'extension VASA Provider doit être activée pour votre instance vCenter Server.

*À propos de cette tâche*

L'utilisation de SSH pour accéder au compte utilisateur diag présente les limites suivantes :

* Vous n'avez droit qu'à un seul compte de connexion par activation de SSH.
* L'accès SSH au compte utilisateur diag est désactivé lorsque l'une des conditions suivantes se produit :
+
** Le délai expire.
+
La session de connexion reste valide jusqu'à minuit le lendemain.

** Vous vous connectez à nouveau en tant qu'utilisateur diag à l'aide de SSH.




.Étapes
. Depuis vCenter Server, ouvrez une console vers VASA Provider.
. Connectez-vous en tant qu'utilisateur de maintenance.
. Entrez `4` pour sélectionner support et diagnostic.
. Entrez `2` pour sélectionner Activer l'accès aux diagnostics à distance.
. Entrez `y` dans la boîte de dialogue Confirmation pour activer l'accès au diagnostic à distance.
. Saisissez un mot de passe pour l'accès au diagnostic à distance.

