---
permalink: manage/enable-services.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez modifier le mot de passe administrateur à l"aide du Gestionnaire d"outils ONTAP.' 
---
= Activez les outils ONTAP pour les services VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gestionnaire pour activer des services tels que VASA Provider, importation de la configuration vVols et reprise après incident (SRA) à l'aide du gestionnaire d'outils ONTAP.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez *Modifier les paramètres de l'appareil* dans la section Présentation.
. Dans la section *Services*, vous pouvez activer des services facultatifs tels que VASA Provider, importer la configuration vVols et SRA (Disaster Recovery) selon vos besoins.
+
Lors de la première activation des services, vous devez créer les informations d'identification du fournisseur VASA et SRA. Ils permettent d'enregistrer ou d'activer les services VASA Provider et SRA sur le serveur vCenter.

+

NOTE: Avant de désactiver les services optionnels, assurez-vous que les serveurs vCenter gérés par les outils ONTAP ne les utilisent pas.

+
L'option *Autoriser l'importation de la configuration vVols* s'affiche uniquement lorsque le service VASA Provider est activé. Cette option active la migration des données vVols des outils ONTAP 9.x vers les outils ONTAP 10.3.


