---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: 'Si vous avez oublié le mot de passe du gestionnaire d"outils ONTAP, vous pouvez réinitialiser les informations d"identification de l"administrateur à l"aide du jeton généré par les outils ONTAP pour la console de maintenance VMware vSphere.' 
---
= Réinitialisez le mot de passe du gestionnaire d'outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez oublié le mot de passe du gestionnaire d'outils ONTAP, vous pouvez réinitialiser les informations d'identification de l'administrateur à l'aide du jeton généré par les outils ONTAP pour la console de maintenance VMware vSphere.

.Étapes
. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Sur l'écran de connexion, sélectionnez l'option *Réinitialiser le mot de passe*.
+
Pour réinitialiser le mot de passe du gestionnaire, vous devez générer le jeton de réinitialisation à l'aide de la console de maintenance des outils ONTAP pour VMware vSphere.

+
.. Dans vCenter Server, ouvrez la console de maintenance
.. Entrez « 2 » pour sélectionner l'option de configuration du système
.. Saisissez « 3 » pour modifier le mot de passe utilisateur « maint ».


. Dans la fenêtre contextuelle de modification du mot de passe, entrez le jeton de réinitialisation du mot de passe, le nom d'utilisateur et les détails du nouveau mot de passe.
. Sélectionnez *Réinitialiser* pour appliquer les modifications. Une fois le mot de passe réinitialisé, vous pouvez utiliser le nouveau mot de passe pour vous connecter.

