---
permalink: manage/update-vcenter-credentials.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez mettre à jour les informations d"identification de vCenter Server et ONTAP à l"aide de la console de maintenance.' 
---
= Mettre à jour les informations d'identification du serveur vCenter et de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à jour l'instance du serveur vCenter et les informations d'identification ONTAP à l'aide de la console de maintenance.

.Avant de commencer
Vous devez disposer des informations d'identification de l'utilisateur de maintenance.

*À propos de cette tâche*

Si vous avez modifié les informations d'identification du serveur vCenter, du ONTAP ou de la LIF de données après le déploiement, vous devez mettre à jour les informations d'identification à l'aide de cette procédure.

.Étapes
. Depuis vCenter Server, ouvrez une console vers VASA Provider.
. Connectez-vous en tant qu'utilisateur de maintenance.
. Entrez `2` pour sélectionner le menu de configuration du système.
. Entrez `9` pour modifier les informations d'identification ONTAP.
. Entrez `10` pour modifier les informations d'identification de vCenter.

